name: Login, Build and Push Container Image to SWR
on: [pull_request, push]

jobs:
  build:
    name: Login, Build and Push Container Image to SWR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Lowercase Variables
        run: echo "IHSACUSTOM_GITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
